# Generated by Django 3.1.7 on 2021-04-12 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20210412_1304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profilePic',
            field=models.FileField(default='static/upload/profilePic/default.gif', upload_to='home/static/upload/profilePic/'),
        ),
    ]
