# Generated by Django 3.1.7 on 2021-04-13 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_user_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=254)),
                ('content', models.CharField(max_length=254)),
                ('creationDate', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
