# Generated by Django 3.1.7 on 2021-04-19 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20210414_0851'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='friendsRequest',
            field=models.ManyToManyField(related_name='_user_friendsRequest_+', to='home.User'),
        ),
        migrations.AddField(
            model_name='user',
            name='userFriends',
            field=models.ManyToManyField(related_name='_user_userFriends_+', to='home.User'),
        ),
    ]
