# Generated by Django 3.1.7 on 2021-04-19 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20210419_1608'),
    ]

    operations = [
        migrations.CreateModel(
            name='FriendRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=254)),
                ('creationDate', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='UserFriends',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=254)),
                ('creationDate', models.DateTimeField()),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='friendsRequest',
        ),
        migrations.RemoveField(
            model_name='user',
            name='userFriends',
        ),
        migrations.AddField(
            model_name='user',
            name='friendRequest',
            field=models.ManyToManyField(to='home.FriendRequest'),
        ),
        migrations.AddField(
            model_name='user',
            name='friends',
            field=models.ManyToManyField(to='home.UserFriends'),
        ),
    ]
