# Generated by Django 3.1.7 on 2021-04-21 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20210419_1813'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=254)),
                ('creationDate', models.DateTimeField()),
                ('user', models.ManyToManyField(to='home.User')),
            ],
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chatId', models.CharField(max_length=508)),
                ('creationDate', models.DateTimeField()),
                ('messages', models.ManyToManyField(to='home.Message')),
            ],
        ),
    ]
